{% set name = "heatrapy" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e0a5603aa019d9b64a5bea85eb17864e5cc51fe790e1d2939e4070bfa1be577e

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [py != 314]

requirements:
  host:
    - python 3.14.*
    - pip
    - setuptools
    - numpy >=2.4.2
  run:
    - python >=3.14
    - numpy >=2.4.2
    - matplotlib-base >=3.10
    - pyparsing >=3.3

test:
  imports:
    - heatrapy
  requires:
    - python 3.14.*
    - pip
  commands:
    - pip check

about:
  home: https://github.com/djsilva99/heatrapy
  summary: 'Library for simulating 1D and 2D heat transfer processes'
  description: |
    This package is a module for simulating dynamic 1D and 2D heat
    transfer processes by using the finite difference method. The
    package is based on thermal objects.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - djsilva99
